"use strict";
module.exports = {

	//events
	'SAVE_PIN_COMPLETE' : 'SAVE_PIN_COMPLETE',
	'GET_USER_PINS_COMPLETE' : 'GET_USER_PINS_COMPLETE',
	'GET_USER_INFO_COMPLETE' : 'GET_USER_INFO_COMPLETE',
	'ADD_COMMENT_COMPLETE' : 'ADD_COMMENT_COMPLETE',
	'GET_COMMENTS_COMPLETE' : 'GET_COMMENTS_COMPLETE',
	'RATE_PIN_COMPLETE' : 'RATE_PIN_COMPLETE',
	'GET_NEWPINS_COMPLETE' : 'GET_NEWPINS_COMPLETE',
	'GET_PININFO_COMPLETE' : 'GET_PININFO_COMPLETE',
	'REMOVE_PIN_COMPLETE' : 'REMOVE_PIN_COMPLETE',
	'REMOVE_COMMENT_COMPLETE' : 'REMOVE_COMMENT_COMPLETE',
	'GET_PINS_BY_HASH' : 'GET_PINS_BY_HASH',
	'INDEX_LIMIT' : 50



};